package payment

import (
	"github.com/stripe/stripe-go/v82"
	"github.com/stripe/stripe-go/v82/paymentintent"
	"github.com/stripe/stripe-go/v82/paymentmethod"
	"github.com/stripe/stripe-go/v82/refund"
)

/*
 * Stripe API docs: https://docs.stripe.com/api
 */

// Set the stripe secret key system-wide for the Stripe SDK to work
func InitStripe(secretKey string) {
	stripe.Key = secretKey
}

// Method to create payment intent, return the client secret of the intent, or error
func CreatePaymentIntent(amount int64, currency stripe.Currency) (*stripe.PaymentIntent, error) {
	params := &stripe.PaymentIntentParams{
		Amount:   stripe.Int64(amount),
		Currency: stripe.String(string(currency)),
		AutomaticPaymentMethods: &stripe.PaymentIntentAutomaticPaymentMethodsParams{
			Enabled: stripe.Bool(true),
		},
	}

	intent, err := paymentintent.New(params)
	if err != nil {
		return nil, err
	}

	return intent, nil
}

// This method is used soley for test, the payment method should be generated by client side (using Stripe.js) to comply with PSI
// compliance
func createPaymentMethodFromToken(token string) (*stripe.PaymentMethod, error) {
	params := &stripe.PaymentMethodParams{
		Type: stripe.String(string(stripe.PaymentMethodTypeCard)),
		Card: &stripe.PaymentMethodCardParams{
			Token: stripe.String(token),
		},
	}

	pm, err := paymentmethod.New(params)
	if err != nil {
		return nil, err
	}

	return pm, nil
}

// Confirm a payment. paymentMethod should be the ID return by Stripe.js in the frontend
func ConfirmPaymentIntent(piID, paymentMethod, returnURL string) (*stripe.PaymentIntent, error) {
	params := &stripe.PaymentIntentConfirmParams{
		PaymentMethod: stripe.String(paymentMethod),
		ReturnURL:     stripe.String(returnURL),
	}

	result, err := paymentintent.Confirm(piID, params)
	if err != nil {
		return nil, err
	}

	return result, nil
}

type RefundReason string

const (
	Duplicate           RefundReason = "duplicate"
	Fraudulent          RefundReason = "fraudulent"
	RequestedByCustomer RefundReason = "requested_by_customer"
)

// If the amount exceed the total amount of the payment intent, it will fail
// Reason for the refund, which is either user-provided (duplicate, fraudulent, or requested_by_customer)
// or generated by Stripe internally (expired_uncaptured_charge).
func CreateRefund(paymentIntentID string, reason RefundReason, amount int64) (*stripe.Refund, error) {
	params := &stripe.RefundParams{
		PaymentIntent: stripe.String(string(paymentIntentID)),
		Amount:        stripe.Int64(amount),
		Reason:        stripe.String(string(reason)),
	}

	refund, err := refund.New(params)
	if err != nil {
		return nil, err
	}

	return refund, nil
}
