package payment

import (
	"github.com/stripe/stripe-go/v82"
	"github.com/stripe/stripe-go/v82/paymentintent"
	"github.com/stripe/stripe-go/v82/paymentmethod"
	"github.com/stripe/stripe-go/v82/refund"
)

/*
 * Stripe API docs: https://docs.stripe.com/api
 */

// Set the stripe secret key system-wide for the Stripe SDK to work
func InitStripe(secretKey string) {
	stripe.Key = secretKey
}

// Method to create payment intent, return the client secret of the intent, or error
func CreatePaymentIntent(amount int64, currency stripe.Currency, key string) (*stripe.PaymentIntent, error) {
	// Create payment intent params
	params := &stripe.PaymentIntentParams{
		Amount:   stripe.Int64(amount),
		Currency: stripe.String(string(currency)),
		AutomaticPaymentMethods: &stripe.PaymentIntentAutomaticPaymentMethodsParams{
			Enabled:        stripe.Bool(true),
			AllowRedirects: stripe.String("never"),
		},
	}

	// Set idempotency key so that payment intent with the same key won't be created anymore -> keep Stripe dashboard cleaner
	params.SetIdempotencyKey(key)

	// Create payment intent
	intent, err := paymentintent.New(params)
	if err != nil {
		return nil, err
	}

	return intent, nil
}

// Cancel an unpaid payment intent
func CancelPaymentIntent(piID string) error {
	_, err := paymentintent.Cancel(piID, &stripe.PaymentIntentCancelParams{})
	return err
}

// This method is used soley for test, the payment method should be generated by client side (using Stripe.js) to comply with PSI
// compliance
func CreatePaymentMethodFromToken(token string) (*stripe.PaymentMethod, error) {
	params := &stripe.PaymentMethodParams{
		Type: stripe.String(string(stripe.PaymentMethodTypeCard)),
		Card: &stripe.PaymentMethodCardParams{
			Token: stripe.String(token),
		},
	}

	pm, err := paymentmethod.New(params)
	if err != nil {
		return nil, err
	}

	return pm, nil
}

// Confirm a payment.
// piID is the payment_intent_id of the payment.
// pmID is the payment_method_id that is generated in the client side (like Stripe.js), since Stripe forbid generate payment
// method in the server side to conform with PCI security standard
func ConfirmPaymentIntent(piID, pmID string) (*stripe.PaymentIntent, error) {
	params := &stripe.PaymentIntentConfirmParams{
		PaymentMethod: stripe.String(pmID),
	}

	result, err := paymentintent.Confirm(piID, params)
	if err != nil {
		return nil, err
	}

	return result, nil
}

// Get payment intent
func GetPaymentIntent(piID string) (*stripe.PaymentIntent, error) {
	intent, err := paymentintent.Get(piID, &stripe.PaymentIntentParams{})
	if err != nil {
		return nil, err
	}
	return intent, nil
}

type RefundReason string

const (
	Duplicate           RefundReason = "duplicate"
	Fraudulent          RefundReason = "fraudulent"
	RequestedByCustomer RefundReason = "requested_by_customer"
)

// If the amount exceed the total amount of the payment intent, it will fail
// Reason for the refund, which is either user-provided (duplicate, fraudulent, or requested_by_customer)
// or generated by Stripe internally (expired_uncaptured_charge).
func CreateRefund(paymentIntentID string, reason RefundReason, amount int64) (*stripe.Refund, error) {
	params := &stripe.RefundParams{
		PaymentIntent: stripe.String(string(paymentIntentID)),
		Amount:        stripe.Int64(amount),
		Reason:        stripe.String(string(reason)),
	}

	refund, err := refund.New(params)
	if err != nil {
		return nil, err
	}

	return refund, nil
}
